//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspnetMvcDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات الحساب.
        /// </summary>
        public static string Account_settings {
            get {
                return ResourceManager.GetString("Account settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة خلطة تصميمة.
        /// </summary>
        public static string Add_Mixing_Design {
            get {
                return ResourceManager.GetString("Add Mixing Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمية الإضافات (ل/م3) .
        /// </summary>
        public static string Addtion_Amount {
            get {
                return ResourceManager.GetString("Addtion Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الإضافات .
        /// </summary>
        public static string Addtion_Type {
            get {
                return ResourceManager.GetString("Addtion Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدة.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتماد.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتماد خلطة تصميمية.
        /// </summary>
        public static string Approve_Mixing_Design {
            get {
                return ResourceManager.GetString("Approve Mixing Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتعمد.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المصانع المعتمدة.
        /// </summary>
        public static string Approved_Factories {
            get {
                return ResourceManager.GetString("Approved Factories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحة.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المساحة المزودة.
        /// </summary>
        public static string Area_Loaded {
            get {
                return ResourceManager.GetString("Area Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفق .
        /// </summary>
        public static string Attached {
            get {
                return ResourceManager.GetString("Attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حضور كسر عينة خرسانة.
        /// </summary>
        public static string Attend_Break_Concrete_Sample {
            get {
                return ResourceManager.GetString("Attend Break Concrete Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتوماتيكي.
        /// </summary>
        public static string Atuomatic {
            get {
                return ResourceManager.GetString("Atuomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط قوة الضغط.
        /// </summary>
        public static string Average_Compressive_Strength {
            get {
                return ResourceManager.GetString("Average Compressive Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل الإنتاج اليومي.
        /// </summary>
        public static string Average_Daily_Production {
            get {
                return ResourceManager.GetString("Average Daily Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجة كسر عينة بلوك.
        /// </summary>
        public static string Block_Entering_Testing_Result {
            get {
                return ResourceManager.GetString("Block Entering Testing Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات عينة البلوك.
        /// </summary>
        public static string Block_Sapmle_Infromation {
            get {
                return ResourceManager.GetString("Block Sapmle Infromation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام البلوك.
        /// </summary>
        public static string Block_System {
            get {
                return ResourceManager.GetString("Block System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجة اختبار عينة بلوك.
        /// </summary>
        public static string Block_Testing_Result {
            get {
                return ResourceManager.GetString("Block Testing Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كسر عينة بلوك.
        /// </summary>
        public static string Break_Block_Sample {
            get {
                return ResourceManager.GetString("Break Block Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كسر عينة خرسانة 28 يوم.
        /// </summary>
        public static string Break_Concrete_28_days {
            get {
                return ResourceManager.GetString("Break Concrete 28 days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كسر عينة خرسانة 7 أيام.
        /// </summary>
        public static string Break_Concrete_7_days {
            get {
                return ResourceManager.GetString("Break Concrete 7 days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حضور كسر عينة خرسانة.
        /// </summary>
        public static string Break_Concrete_Sample {
            get {
                return ResourceManager.GetString("Break Concrete Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهادات المعايرة .
        /// </summary>
        public static string Calibration_certificates {
            get {
                return ResourceManager.GetString("Calibration certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصدر الاسمنت.
        /// </summary>
        public static string Cement_Source {
            get {
                return ResourceManager.GetString("Cement Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الاسمنت .
        /// </summary>
        public static string Cement_Type {
            get {
                return ResourceManager.GetString("Cement Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن الاسمنت (كجم).
        /// </summary>
        public static string Cement_Weight {
            get {
                return ResourceManager.GetString("Cement Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظافة .
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضغط الزر للذهاب.
        /// </summary>
        public static string Click_below_button_to_go {
            get {
                return ResourceManager.GetString("Click below button to go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل .
        /// </summary>
        public static string Client_Name {
            get {
                return ResourceManager.GetString("Client Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعمدة .
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل التجاري.
        /// </summary>
        public static string Commercial_Register {
            get {
                return ResourceManager.GetString("Commercial Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوة الضغط.
        /// </summary>
        public static string Compressive_Strength {
            get {
                return ResourceManager.GetString("Compressive Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوة ضغط مكعب البلوك.
        /// </summary>
        public static string Compressive_Strength_of_Block_Cube {
            get {
                return ResourceManager.GetString("Compressive Strength of Block Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوة ضغط مكعب خرسانة.
        /// </summary>
        public static string Compressive_Strength_of_Concrete_Cube {
            get {
                return ResourceManager.GetString("Compressive Strength of Concrete Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجة كسر عينة خرسانه.
        /// </summary>
        public static string Concrete_Entering_Testing_Result {
            get {
                return ResourceManager.GetString("Concrete Entering Testing Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPa رتبة العينة نيوتن (نيوتن / مم2).
        /// </summary>
        public static string Concrete_Rank {
            get {
                return ResourceManager.GetString("Concrete Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عينة الخرسانة.
        /// </summary>
        public static string Concrete_Sample {
            get {
                return ResourceManager.GetString("Concrete Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام الخرسانة.
        /// </summary>
        public static string Concrete_System {
            get {
                return ResourceManager.GetString("Concrete System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة حرارة الخرسانة (مْ).
        /// </summary>
        public static string Concrete_Tempereture {
            get {
                return ResourceManager.GetString("Concrete Tempereture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجة اختبار عينة خرسانة.
        /// </summary>
        public static string Concrete_Testing_Result {
            get {
                return ResourceManager.GetString("Concrete Testing Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدام الخرسانة.
        /// </summary>
        public static string Concrete_Using {
            get {
                return ResourceManager.GetString("Concrete Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل مصنع جديد.
        /// </summary>
        public static string Create_Factory {
            get {
                return ResourceManager.GetString("Create Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مستخدم.
        /// </summary>
        public static string Create_User {
            get {
                return ResourceManager.GetString("Create User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدى تحمل الكسر.
        /// </summary>
        public static string Crushing_Load {
            get {
                return ResourceManager.GetString("Crushing Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفوض.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبب الرفض.
        /// </summary>
        public static string Decline_Reason {
            get {
                return ResourceManager.GetString("Decline Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفوض.
        /// </summary>
        public static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المصانع المرفوضة.
        /// </summary>
        public static string Declined_Factories {
            get {
                return ResourceManager.GetString("Declined Factories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استلام عينة بلوك.
        /// </summary>
        public static string Deliver_Block {
            get {
                return ResourceManager.GetString("Deliver Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استلام عينة خرسانه .
        /// </summary>
        public static string Deliver_Concrete {
            get {
                return ResourceManager.GetString("Deliver Concrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استلام عينة خرسانة.
        /// </summary>
        public static string Deliver_Concrete_Samples {
            get {
                return ResourceManager.GetString("Deliver Concrete Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاستلام.
        /// </summary>
        public static string Deliver_Done {
            get {
                return ResourceManager.GetString("Deliver Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل .
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايعاد (الطول * العرض * الارتفاع ) ملم.
        /// </summary>
        public static string Dim {
            get {
                return ResourceManager.GetString("Dim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الهبوط (مم).
        /// </summary>
        public static string Down_Amount {
            get {
                return ResourceManager.GetString("Down Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل البيانات.
        /// </summary>
        public static string Enter_Data {
            get {
                return ResourceManager.GetString("Enter Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ انتهاء صلاحية الخلطة.
        /// </summary>
        public static string Expiary_Date {
            get {
                return ResourceManager.GetString("Expiary Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة المصانع.
        /// </summary>
        public static string Factories_List {
            get {
                return ResourceManager.GetString("Factories List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل المصنع.
        /// </summary>
        public static string Factory_Details {
            get {
                return ResourceManager.GetString("Factory Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني للمصنع .
        /// </summary>
        public static string Factory_Email {
            get {
                return ResourceManager.GetString("Factory Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم  فاكس المصنع .
        /// </summary>
        public static string Factory_Fax {
            get {
                return ResourceManager.GetString("Factory Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المصنع.
        /// </summary>
        public static string Factory_Info {
            get {
                return ResourceManager.GetString("Factory Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المصنع.
        /// </summary>
        public static string Factory_Name {
            get {
                return ResourceManager.GetString("Factory Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم هاتف المصنع .
        /// </summary>
        public static string Factory_Phone_Number {
            get {
                return ResourceManager.GetString("Factory Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المصنع.
        /// </summary>
        public static string Factory_Status {
            get {
                return ResourceManager.GetString("Factory Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التزام العاملين بالمصنع بلبس الكمامات.
        /// </summary>
        public static string Factory_workers_commitment_to_wear_masks {
            get {
                return ResourceManager.GetString("Factory workers commitment to wear masks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المصنع.
        /// </summary>
        public static string Factroy {
            get {
                return ResourceManager.GetString("Factroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع المصنع.
        /// </summary>
        public static string Factroy_Location {
            get {
                return ResourceManager.GetString("Factroy Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المصنع.
        /// </summary>
        public static string Factroy_Type {
            get {
                return ResourceManager.GetString("Factroy Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم زيارة المصنع.
        /// </summary>
        public static string Factroy_Visit_Number {
            get {
                return ResourceManager.GetString("Factroy Visit Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الملف .
        /// </summary>
        public static string File_Name {
            get {
                return ResourceManager.GetString("File Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات عامة .
        /// </summary>
        public static string Global_Information {
            get {
                return ResourceManager.GetString("Global Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الذهاب.
        /// </summary>
        public static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترخيص الصناعي.
        /// </summary>
        public static string Industrial_license {
            get {
                return ResourceManager.GetString("Industrial license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أساسيات .
        /// </summary>
        public static string Infastructure {
            get {
                return ResourceManager.GetString("Infastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتورة .
        /// </summary>
        public static string Invoice_Number {
            get {
                return ResourceManager.GetString("Invoice Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهادات الأيزو .
        /// </summary>
        public static string ISO_certificates {
            get {
                return ResourceManager.GetString("ISO certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسمى الوظيفي.
        /// </summary>
        public static string Job_Title {
            get {
                return ResourceManager.GetString("Job Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المختبر.
        /// </summary>
        public static string Laboratory {
            get {
                return ResourceManager.GetString("Laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وجود مختبر .
        /// </summary>
        public static string Laboratory_Exist {
            get {
                return ResourceManager.GetString("Laboratory Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاشة المختبر.
        /// </summary>
        public static string Laboratory_Screen {
            get {
                return ResourceManager.GetString("Laboratory Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواجد مهندس المختبر.
        /// </summary>
        public static string Laboratroy_Engineer_Exist {
            get {
                return ResourceManager.GetString("Laboratroy Engineer Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  خط الطول .
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Login_to_Your_Account {
            get {
                return ResourceManager.GetString("Login to Your Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط العرض.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر النظام الذي تريد استخدامه.
        /// </summary>
        public static string Make_Choice {
            get {
                return ResourceManager.GetString("Make Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني لمدير المصنع .
        /// </summary>
        public static string Manager__Email {
            get {
                return ResourceManager.GetString("Manager  Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم مدير المصنع.
        /// </summary>
        public static string Manager__Name {
            get {
                return ResourceManager.GetString("Manager  Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم جوال مدير المصنع .
        /// </summary>
        public static string Manager__PhoneNumber {
            get {
                return ResourceManager.GetString("Manager  PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤهل العلمي وسنوات الخبرة.
        /// </summary>
        public static string Manager_Experience__years_ {
            get {
                return ResourceManager.GetString("Manager Experience (years)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يدوي.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخلطة التصميمية.
        /// </summary>
        public static string Mix_Design {
            get {
                return ResourceManager.GetString("Mix Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الخلطة التصميمية.
        /// </summary>
        public static string Mix_Design_Details {
            get {
                return ResourceManager.GetString("Mix Design Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الخلاطة .
        /// </summary>
        public static string Mixer_Number {
            get {
                return ResourceManager.GetString("Mixer Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الانتقال.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترخيص البلدية .
        /// </summary>
        public static string Municipality_license {
            get {
                return ResourceManager.GetString("Municipality license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصي.
        /// </summary>
        public static string My_profile {
            get {
                return ResourceManager.GetString("My profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسلسل .
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مرفق .
        /// </summary>
        public static string Not_Attached {
            get {
                return ResourceManager.GetString("Not Attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات .
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإشعارات.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بواسطة نقرة لتنقية المعلومات .
        /// </summary>
        public static string Nqraa_Solutions {
            get {
                return ResourceManager.GetString("Nqraa Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخرى.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني لصاحب المصنع .
        /// </summary>
        public static string Owner_Email {
            get {
                return ResourceManager.GetString("Owner Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المالك والمديرين.
        /// </summary>
        public static string Owner_Info {
            get {
                return ResourceManager.GetString("Owner Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم صاحب المصنع .
        /// </summary>
        public static string Owner_Name {
            get {
                return ResourceManager.GetString("Owner Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم جوال صاحب المصنع.
        /// </summary>
        public static string Owner_Phone_Number {
            get {
                return ResourceManager.GetString("Owner Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد انتظار الاعتماد.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصانع قيد الموافقة.
        /// </summary>
        public static string Pending_Factories {
            get {
                return ResourceManager.GetString("Pending Factories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علامة الجودة .
        /// </summary>
        public static string performance_sign {
            get {
                return ResourceManager.GetString("performance sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        public static string Pervious {
            get {
                return ResourceManager.GetString("Pervious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        public static string Phone_Nubmer {
            get {
                return ResourceManager.GetString("Phone Nubmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة .
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق بريد المصنع .
        /// </summary>
        public static string Post_Code {
            get {
                return ResourceManager.GetString("Post Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخذ عينة بلوك .
        /// </summary>
        public static string Prepare_Block {
            get {
                return ResourceManager.GetString("Prepare Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحضير عينة خرسانة.
        /// </summary>
        public static string Prepare_Concrete {
            get {
                return ResourceManager.GetString("Prepare Concrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحضيرات العينات .
        /// </summary>
        public static string Prepare_Samples {
            get {
                return ResourceManager.GetString("Prepare Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطاقة الإنتاجية.
        /// </summary>
        public static string Produce_Power {
            get {
                return ResourceManager.GetString("Produce Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراقبة الجودة.
        /// </summary>
        public static string Quality_Control {
            get {
                return ResourceManager.GetString("Quality Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جودة التحكم في الغبار المتطاير من الخلاطة.
        /// </summary>
        public static string Quality_control_of_flying_dust_from_the_mixer {
            get {
                return ResourceManager.GetString("Quality control of flying dust from the mixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني لمهندس الجودة.
        /// </summary>
        public static string Quality_Engineer__Email {
            get {
                return ResourceManager.GetString("Quality Engineer  Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم جوال مهندس الجودة .
        /// </summary>
        public static string Quality_Engineer__PhoneNumber {
            get {
                return ResourceManager.GetString("Quality Engineer  PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤهل العلمي وسنوات الخبرة .
        /// </summary>
        public static string Quality_Engineer_Experience__years_ {
            get {
                return ResourceManager.GetString("Quality Engineer Experience (years)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم مهندس الجودة .
        /// </summary>
        public static string Quality_Engineer_Name {
            get {
                return ResourceManager.GetString("Quality Engineer Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جودة نظافة الموقع .
        /// </summary>
        public static string Quality_of_Factory_Cleaning {
            get {
                return ResourceManager.GetString("Quality of Factory Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراقبة جودة مصانع الخرسانة والبلوك.
        /// </summary>
        public static string Quanlity_Control_System_for_Concrete {
            get {
                return ResourceManager.GetString("Quanlity Control System for Concrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التقرير.
        /// </summary>
        public static string Report_Date {
            get {
                return ResourceManager.GetString("Report Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التقرير .
        /// </summary>
        public static string Report_Number {
            get {
                return ResourceManager.GetString("Report Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير زيارة مصنع البلوك.
        /// </summary>
        public static string Report_Visit_Block_Factory {
            get {
                return ResourceManager.GetString("Report Visit Block Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير زيارة مصنع خرسانة.
        /// </summary>
        public static string Report_Visit_Concrete_Factory {
            get {
                return ResourceManager.GetString("Report Visit Concrete Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات والحسابات.
        /// </summary>
        public static string Roles_and_Accounts {
            get {
                return ResourceManager.GetString("Roles and Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسقف .
        /// </summary>
        public static string Roofs {
            get {
                return ResourceManager.GetString("Roofs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الركام 4/3 (كجم).
        /// </summary>
        public static string Rubble_3_4 {
            get {
                return ResourceManager.GetString("Rubble 3/4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الركام 8/3 (كجم).
        /// </summary>
        public static string Rubble_3_8 {
            get {
                return ResourceManager.GetString("Rubble 3/8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العينة .
        /// </summary>
        public static string Sample_Number {
            get {
                return ResourceManager.GetString("Sample Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت العينة.
        /// </summary>
        public static string Sample_Time {
            get {
                return ResourceManager.GetString("Sample Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر نوع المصنع.
        /// </summary>
        public static string Select_Factroy_Type {
            get {
                return ResourceManager.GetString("Select Factroy Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار رتبة.
        /// </summary>
        public static string Select_Rnak {
            get {
                return ResourceManager.GetString("Select Rnak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتوماتيكي جزئي.
        /// </summary>
        public static string Semi_Atuomatic {
            get {
                return ResourceManager.GetString("Semi Atuomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادت .
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكل.
        /// </summary>
        public static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رؤية كل الإشعارات.
        /// </summary>
        public static string Show_all_notifications {
            get {
                return ResourceManager.GetString("Show all notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string Sign_In {
            get {
                return ResourceManager.GetString("Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string Sign_out {
            get {
                return ResourceManager.GetString("Sign out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل .
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل كمصنع جديد.
        /// </summary>
        public static string Signup_as_new_Factory {
            get {
                return ResourceManager.GetString("Signup as new Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رش الركام في فصل الصيف.
        /// </summary>
        public static string Spray_debris_in_the_summer {
            get {
                return ResourceManager.GetString("Spray debris in the summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة .
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوة الأولى.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوة الثانية.
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوة الثالثة.
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوة الرابعة.
        /// </summary>
        public static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاختبار.
        /// </summary>
        public static string Test_Date {
            get {
                return ResourceManager.GetString("Test Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتائج الاختبارات.
        /// </summary>
        public static string TestingResults {
            get {
                return ResourceManager.GetString("TestingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخلطات التصميمية المستخدمة.
        /// </summary>
        public static string The_design_mixture_used {
            get {
                return ResourceManager.GetString("The design mixture used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وجود ملدنات في سيارة نقل الخرسانة.
        /// </summary>
        public static string The_presence_of_plasticizers_in_the_concrete_transport_vehicle {
            get {
                return ResourceManager.GetString("The presence of plasticizers in the concrete transport vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواجد مهندس المختبر.
        /// </summary>
        public static string The_presence_of_the_laboratory_engineer {
            get {
                return ResourceManager.GetString("The presence of the laboratory engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الخلاطات بالمصنع .
        /// </summary>
        public static string Total_Mixers_Number {
            get {
                return ResourceManager.GetString("Total Mixers Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الشاحنات .
        /// </summary>
        public static string Total_Truckers_Number {
            get {
                return ResourceManager.GetString("Total Truckers Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الشاحنة .
        /// </summary>
        public static string Trucker_Number {
            get {
                return ResourceManager.GetString("Trucker Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوزن الكلي.
        /// </summary>
        public static string Unit_Weight {
            get {
                return ResourceManager.GetString("Unit Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرفاق.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string User_name {
            get {
                return ResourceManager.GetString("User name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب الشخصي.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الزيارة.
        /// </summary>
        public static string Visit_Date {
            get {
                return ResourceManager.GetString("Visit Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع الزيارة.
        /// </summary>
        public static string Visit_Location {
            get {
                return ResourceManager.GetString("Visit Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقارير الزيارة.
        /// </summary>
        public static string Visit_Reports {
            get {
                return ResourceManager.GetString("Visit Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير زيارة مصنع بلوك.
        /// </summary>
        public static string Visting__Block_Factroy_Report {
            get {
                return ResourceManager.GetString("Visting  Block Factroy Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحجم.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمل المغسول (كجم) .
        /// </summary>
        public static string Washed_Sand {
            get {
                return ResourceManager.GetString("Washed Sand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة حرارة الماء (مْ) .
        /// </summary>
        public static string Water_Tempreture {
            get {
                return ResourceManager.GetString("Water Tempreture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن الماء (كجم) .
        /// </summary>
        public static string Water_Weight {
            get {
                return ResourceManager.GetString("Water Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة حرارة الجو  (مْ).
        /// </summary>
        public static string Weather_Tempreture {
            get {
                return ResourceManager.GetString("Weather Tempreture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوزن (كغ).
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمل الأبيض (كجم) .
        /// </summary>
        public static string White_Sand {
            get {
                return ResourceManager.GetString("White Sand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم .
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
